### ISSUE TITLE
Unable to update line sub WEB_SERVER { "localhost:5000" } in file /config/DBDefs.pm

### ISSUE THREAD

**Issue by nodecentral** [linuxserver/docker-musicbrainz#87] opened 2021-02-23 11:49 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I should be able to update the sub WEB_SERVER { "localhost:5000" }after the creation of the containter

The https://hub.docker.com/r/linuxserver/musicbrainz instructions claim..

_"If you did not set WEBADDRESS env variable, then AFTER iniatilisation is complete you will need to edit the line sub WEB_SERVER { "localhost:5000" } in file /config/DBDefs.pm changing localhost to the ip of your host, this is to allow css to display properly"_

## Current Behavior
Any changes I make to the sub WEB_SERVER { "localhost:5000" } line in  /config/DBDefs.pm areoverwritted on reboot with the address provided via the   -e WEBADDRESS=<ip of host>

## Steps to Reproduce
Create a container with a specific IP in the   -e WEBADDRESS=<ip of host> \
Once installed, go in and edit the sub WEB_SERVER { "localhost:5000" } in file /config/DBDefs.pm with a new IP
Reboot 
Go back into the DBDefs.pm fiel to see that it's reverted back to the original one.

## Environment
**OS:**
Linux QNAP NAS
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
Installed as part of Containter Statition

## Command used to create docker container (run/create/compose/screenshot)
````
docker run -d \
  --name=musicbrainz \
  -e PUID=501\
  -e PGID=100 \
  -e TZ=Europe/London \
  -e BRAINZCODE=fioqfioqwoniqwfoniqwfoiq \
  -e WEBADDRESS=10.10.10.84 \
  -p 5000:5000 \
  -v /share/musicbrainz/config:/config \
  -v /share/musicbrainz/config:/data
````

**Comment by tobbenb** [comment] 2021-02-23 12:07
It's not strange that the setting is reverted as long as you have set the env variable. That's how it works. Of you want to change the value, then change it in the env variable.

**Comment by nodecentral** [comment] 2021-02-23 12:54
> It's not strange that the setting is reverted as long as you have set the env variable

Agreed, so it sounds like the best solution (at least for me, who is using dhcp) is not to submit that environmental variable at all ?

I’ll give that a go, as It’ll be interesting to see how that works, and if after a reboot if reverts back to any default.

**Comment by tobbenb** [comment] 2021-02-23 15:53
Why not set a static IP given by DHCP?
You either set the env variable or change the config file. Not both. Do what is easiest for you.

**Comment by nodecentral** [comment] 2021-02-23 19:57
> Why not set a static IP given by DHCP?

Hi @tobbenb - how would I do that when I’m using a virtual switch, as it seems to generate a new MAC every time I recreate the container?

**Comment by tobbenb** [comment] 2021-02-23 21:02
I have no idea how your setup is, so can't tell you how to do it.
You do not say what is getting the IP, if it's the host or the container. And what is a virtual switch? 
But this is not related to the container, so hop on our discord to get more help. Closing this as it's not a bug.

**Closed as completed by tobbenb** 2021-02-23 21:02 UTC
